In [26]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

data = pd.read_csv("iris.csv")

# it is just fill catogery data
# data['species'] = data['species'].fillna(data['species'].mode()[0])
# data['species'] = data['species'].map({'setosa':0,'virginica':1,'versicolor':2})

# this converts category data into number as well as convert into number
le = LabelEncoder()
st = StandardScaler()
min_max = MinMaxScaler()

data['species'] = le.fit_transform(data['species'])

X = data[['sepal_length','sepal_width','petal_length','petal_width']]
y = data['species']

print("MIN-MAX SCALED DATA: \n")
# print(pd.DataFrame(min_max_scaled))
print("STANDERD SCALED DATA: \n")
# print(pd.DataFrame(st_scaled))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = st.fit_transform(X_train)  # do not scale test data in fit_transform, it causes leak information
X_test = st.transform(X_test)

# model = LogisticRegression()
# model.fit(X_train, y_train)

model = KNeighborsClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(y_pred)

new_train = [5.4, 3.9, 1.7, 0.4]
result = model.predict([new_train])
print(le.inverse_transform(result))

print(data.head())
print(data.isnull().sum())
print("Logistic Accuracy:", accuracy_score(y_test, model.predict(X_test)))
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)

MIN-MAX SCALED DATA: 

STANDERD SCALED DATA: 

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
['virginica']
   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
Logistic Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
